Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [186]:
import numpy as np

In [187]:
a = np.linspace(12, 24, num = 12, endpoint = False)
a

array([12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [188]:
a1 = a.reshape(3, 4)
a1

array([[12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.]])

In [189]:
a2 = a.reshape(4, 3)
a2

array([[12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [190]:
a3 = a.reshape(2, 6)
a3

array([[12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [191]:
a4 = a.reshape(6, 2)
a4

array([[12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.],
       [20., 21.],
       [22., 23.]])

In [194]:
a5 = a.reshape(12, 1)
a5

array([[12.],
       [13.],
       [14.],
       [15.],
       [16.],
       [17.],
       [18.],
       [19.],
       [20.],
       [21.],
       [22.],
       [23.]])

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [195]:
aa1 = a.reshape(-1, 1)
aa1

array([[12.],
       [13.],
       [14.],
       [15.],
       [16.],
       [17.],
       [18.],
       [19.],
       [20.],
       [21.],
       [22.],
       [23.]])

In [196]:
aa2 = a.reshape(-1,2)
aa2

array([[12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.],
       [20., 21.],
       [22., 23.]])

In [197]:
aa3 = a.reshape(3,-1)
aa3

array([[12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.]])

In [198]:
aa4 = a.reshape(4,-1)
aa4

array([[12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [199]:
aa5 = a.reshape(6,-1)
aa5

array([[12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.],
       [20., 21.],
       [22., 23.]])

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

да

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [200]:
a = np.random.standard_normal(12)
a = a.reshape(3, 4)
a.mean(), a.std(),a


(0.11017077828611953,
 0.8691213650808443,
 array([[ 1.03099952,  0.93128012, -0.83921752, -0.30921238],
        [ 0.33126343,  0.97554513, -0.47917424, -0.18565898],
        [-1.10633497, -1.19620662,  0.81252582,  1.35624003]]))

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [201]:
a = np.arange(20, 0, -2)
a


array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [202]:
b = np.arange(20, 1, -2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [203]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [204]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [205]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [206]:
v.size

10

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [207]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [208]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [209]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [210]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [211]:
B.size

16

In [212]:
np.linalg.inv(B)

LinAlgError: Singular matrix

B - это Сингулярная матрица 
Если определитель матрицы  𝐴  равен  𝑑 , то определитель обратной матрицы всегда будет равен  1/𝑑 . Именно поэтому матрицы с определителем, равным  0 , обращать нельзя.

In [213]:
np.linalg.det(B)

0.0

Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [214]:
np.random.seed(42)
np.random.random(10)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 


In [215]:
a = np.random.randint(0, 16, 16)

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [216]:
C = a.reshape(4, 4)
C

array([[ 5,  4,  1,  7],
       [11, 13,  5,  1],
       [15, 11,  4,  0],
       [11,  9,  5, 12]])

In [217]:
C = np.dot(C, 10)
C

array([[ 50,  40,  10,  70],
       [110, 130,  50,  10],
       [150, 110,  40,   0],
       [110,  90,  50, 120]])

In [218]:
D = C + B
D

array([[ 55,  54,  33, 102],
       [124, 180, 136, 132],
       [173, 196, 189, 212],
       [142, 212, 262, 422]])

In [219]:
np.linalg.det(D)


72557599.99999987

In [220]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00980683, -0.01670645,  0.02091966, -0.00765406],
       [ 0.00539875,  0.02483241, -0.02053706,  0.0012448 ],
       [-0.02579633, -0.00913233,  0.01239567,  0.00286448],
       [ 0.01000364, -0.00118361, -0.00441801,  0.00254143]])

In [221]:
np.linalg.matrix_rank(D)

4

Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [222]:
D_inv = np.where(D_inv < 0, 0, D_inv)
D_inv = np.where(D_inv > 0, 1, D_inv)
D_inv

array([[1., 0., 1., 0.],
       [1., 1., 0., 1.],
       [0., 0., 1., 1.],
       [1., 0., 0., 1.]])

In [223]:
E = np.where(D_inv == 1, B, C)


In [224]:
E

array([[  5,  40,  23,  70],
       [ 14,  50,  50, 122],
       [150, 110, 149, 212],
       [ 32,  90,  50, 302]])